version: '3'

services:
  app:
    env_file:
      - app/.env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    env_file:
      - app/.env
    image: mysql:latest
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
