version: '3'

services:
  api:
    container_name: provenance-api
    env_file:
      - app/.env
    build: .
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started

  db:
    container_name: provenance-db
    image: mysql:latest
    env_file:
      - app/.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-p$MYSQL_ROOT_PASSWORD", "ping", "-h", "localhost", "--protocol","tcp"]
      start_period: 10s 
      interval: 5s
      timeout: 30s
      retries: 30

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak
    ports:
      - "8080:8080"
    environment:
      KEYCLOAK_ADMIN: admin 
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: 
      - start-dev 
      - --import-realm
    volumes:
      - ./app/authentication/keycloak-realm.json:/opt/keycloak/data/import/realm.json

volumes:
  db_data:
